name = "Ashes to Ash's"
author = "Ash"
version = "6.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fdc8280952652f5ed0ab76f472f217795f67599780aad144fae92a8a5eab1578"

[versions]
minecraft = "1.19"
quilt = "0.17.3"
