on:
  push:
    branches:
      - main
    
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir tmp
          cp -rfL src/{universal,overrides/client}/* tmp/
          cd tmp
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: tmp/**
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir tmp
          cp -rfL src/{universal,overrides/server}/* tmp/
          cd tmp

          curl -L -o installer.jar 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.10.2/fabric-installer-0.10.2.jar'
          java -jar installer.jar server -downloadMinecraft -mcversion 1.18
          rm installer.jar
      - uses: actions/upload-artifact@v2
        with:
          name: server
          path: tmp/**
