on:
  push:
    branches:
      - main
    
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir tmp
          cp -rfL src/universal/* tmp/
          cd tmp

          mkdir -p bin
          curl -L -o bin/version.json 'https://fabricmc.net/download/technic/?yarn=1.17.1+build.63&loader=0.12.5'
      - uses: actions/upload-artifact@v2
        with:
          name: client
          path: tmp/**
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir tmp
          cp -rfL src/{universal,overrides/server}/* tmp/
          cd tmp

          curl -L -o installer.jar 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/0.9.0/fabric-installer-0.9.0.jar'
          java -jar installer.jar server -downloadMinecraft -mcversion 1.17.1
          rm installer.jar
      - uses: actions/upload-artifact@v2
        with:
          name: server
          path: tmp/**
