on:
  push:
    tags:
      - v*.*.*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        id: semver
        with:
          tag: ${{ github.ref }}
      - uses: ciiiii/toml-editor@1.0.0
        with:
          file: src/pack.toml
          key: version
          value: ${{ steps.semver.outputs.non-prefixed }}
      - run: |
          go install github.com/packwiz/packwiz@latest
          packwiz modrinth export --meta-folder-base src --pack-file src/pack.toml -o all.mrpack
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            all.mrpack