on:
  push:
    tags:
      - v*.*.*
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: LykkeBusiness/get-semver-from-tag-action@v1.0.2
        id: semver
        with:
          tag: ${{ github.ref }}
      - uses: ciiiii/toml-editor@1.0.0
        with:
          file: src/pack.toml
          key: version
          value: ${{ steps.semver.outputs.non-prefixed }}
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: packwiz/packwiz
          workflow: go.yml
          workflow_conclusion: success
          branch: master
          event: push
          name: Linux 64-bit x86
      - run: |
          chmod +x packwiz
          ./packwiz modrinth export --meta-folder-base src --pack-file src/pack.toml -o all.mrpack
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            all.mrpack